[database]
url="postgres://cloudthink:cloudthink@localhost/cts?currentSchema=public"
max_connections=100
min_connections=5
connect_timeout=8
idle_timeout=8
max_lifetime=8
sqlx_logging=true
[log]
debug=true