version: "3"

services:
  cts-admin-server:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    container_name: cts-admin-server
    image: tanghy/cts-server:2.0
    restart: unless-stopped
    depends_on:
      - postgis
    ports:
      - "3000:3000"
    networks:
      - net_cts # 使用指定声明的网咯
    volumes: # 将本地目录映射到容器内的目录
      - ./volume/server/config.toml:/app/config.toml   # 将本地 data 目录映射到容器内的 /var/lib/postgresql/data 目录
  # cts-admin-web:
  #   container_name: cts-admin-web
  #   image: nginx:1.17.9-alpine
  #   restart: unless-stopped
  #   environment:
  #     - LANG=zh_CN.UTF-8
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./volume/nginx:/etc/nginx/conf.d
  #     - ./volume/apps:/apps
  #     - ./volume/nginx/logs:/var/log/nginx
  #     - ./volume/nginx/image:/image
  #   networks:
  #     - net_cts

  cts-admin-web:
    # build: /Users/tanghy/develop/vue/vue-vben-admin/
    image: tanghy/cts-web
    container_name: cts-admin-web
    restart: unless-stopped
    depends_on:
      - cts-admin-server
    ports:
      - "80:80"
    networks:
      - net_cts # 使用指定声明的网咯

  # cts-tiled-server:
  #   image: cts/tiled-server:latest
  #   container_name: cts-tiled
  #   restart: unless-stopped
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./volume/cts-tile/config:/app/config
  #     - ./volume/cts-tile/mbtiles:/app/mbtiles
  #     - ./volume/cts-tile/fonts:/app/fonts
  #   networks:
  #     - net_cts
  #   privileged: true
  mbtileserver:
    image: ghcr.io/consbio/mbtileserver:latest
    container_name: mbtileserver1
    entrypoint: /mbtileserver --enable-reload-signal
    restart: always
    ports:
        - 8080:8000
    volumes:
        - ./volume/mbtiles:/tilesets
    networks:
      - net_cts # 使用指定声明的网咯

  postgis:
    image: kartoza/postgis:13.0  # 使用 postgis/postgis 镜像
    container_name: cts-postgis
    restart: unless-stopped        # 出现错误时自动重启
    environment: # 设置环境变量
      # POSTGRES_DB: mydatabase     # 数据库名为 mydatabase
      POSTGRES_USER: root       # 用户名
      POSTGRES_PASSWORD: 123456   # 密码
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5432:5432"        # 将本地端口 5432 映射到容器内的 5432 端口
    volumes: # 将本地目录映射到容器内的目录
      - ./volume/postgis:/var/lib/postgresql   # 将本地 data 目录映射到容器内的 /var/lib/postgresql/data 目录
    networks:
      - net_cts # 使用指定声明的网咯

# 声明网络，在外部容器中可进行链接（link）来达到在其他容器中使用postgis容器（所在的网络）
networks:
  net_cts:
