//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub use super::sys_api::Entity as SysApi;
pub use super::sys_menu::Entity as SysMenu;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_tenant::Entity as SysTenant;
pub use super::sys_user::Entity as SysUser;
