//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub code: String,
    pub form_template_id: String,
    pub data_table_name: String,
    pub total: i32,
    pub r#type: i32,
    pub status: i32,
    pub description: Option<String>,
    pub remark: Option<String>,
    pub tenant_id: String,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sys_tenant::Entity",
        from = "Column::TenantId",
        to = "super::sys_tenant::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SysTenant,
}

impl Related<super::sys_tenant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SysTenant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
