[package]
name = "web"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
axum.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber = {workspace=true}
response_utils.workspace = true